export const rsbclBoardOfDirectors = [
  {
    sN: 1,
    name: "Dr. Krishna Kant Pathak, IAS",
    address: "Secretary, Finance (Revenue)",
    designation: "Chairman-cum-Managing Director",
    phoneNo: "0141-2227711",
  },
  {
    sN: 2,
    name: "Sh. Ravi Kumar Surpur, IAS",
    address: "Commissioner, Commercial Tax Department, Rajasthan",
    designation: "Director",
    phoneNo: "0141-2227552",
  },
  {
    sN: 3,
    name: "Sh. Naresh Kumar Thakral, IAS",
    address: "Special Secretary, Finance (Expenditure), Jaipur",
    designation: "Director",
    phoneNo: "0141-2227625",
  },
  {
    sN: 4,
    name: "Sh. Ansh Deep, IAS",
    address: "Commissioner, Excise Department, Rajasthan",
    designation: "Director",
    phoneNo: "0294 - 2524911",
  },
  {
    sN: 5,
    name: "Smt. Shivangi Swarnkar, IAS",
    address: "Commissioner, Medical Education Department",
    designation: "Woman Director",
    phoneNo: "0141-2606533",
  },
  {
    sN: 6,
    name: "Sh. Jagveer Singh, RAS",
    address: "Executive Director, RSBCL",
    designation: "Director",
    phoneNo: "0141-2744231",
  },
  {
    sN: 7,
    name: "VACANT",
    address: "Independent Director",
    designation: "Independent Director",
    phoneNo: "0141-",
  },
  {
    sN: 8,
    name: "VACANT",
    address: "Independent Director",
    designation: "Independent Director",
    phoneNo: "0141-",
  },
];
